version: '3.1'

services:
  mongo:
    image: mongo:4.4.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: test
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
      - ./mongo-initial-scripts:/docker-entrypoint-initdb.d
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      MONGO_USER: root
      MONGO_PASSWORD: password
      MONGO_HOST: mongo
      MONGO_DATABASE: test
    depends_on:
      - mongo
volumes:
  mongodata:
