version: '3.1'
services:
  mysql:
    image: mysql:5.7.31
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: testdb
    ports:
      - 3306:3306
    volumes:
      - mysqldata:/var/lib/mysql
  redis:
    ports:
      - 6379:6379
    image: redis:6.0.8
    restart: always
    volumes:
      - redisdata:/data
volumes:
  mysqldata:
  redisdata:
