version: '3.1'
services:
  mysql:
    image: mysql:5.7.31
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: testdb
    ports:
      - 3306:3306
    volumes:
      - mysqldata:/var/lib/mysql
volumes:
  mysqldata:
