spring:
  datasource:
    url: jdbc:mysql://localhost/testdb
    username: admin
    password: password
mybatis:
  config-location: classpath:mybatis/root-config.xml
logging:
  level:
    com.github.gcnyin.mybatisdemo.mapper: TRACE
