spring:
  datasource:
    url: jdbc:mysql://localhost/testdb
    username: admin
    password: password
mybatis:
  configuration:
    logImpl: org.apache.ibatis.logging.slf4j.Slf4jImpl
logging:
  level:
    com.github.gcnyin.mybatisdemo.dao:
      UserMapper: TRACE
